local P1Config = {
    Version = "P1.0.0",
    RegionId = "R1_ENTRY_MARSH",
    SpawnName = "R1_ENTRY_SPAWN",
    ExtractionName = "MAIN_EXTRACTION",
    EvidenceCrateName = "P1_EVIDENCE_CRATE",
    EvidenceItemId = "EVIDENCE_CAPSULE",
    ObjectiveId = "P1_COLLECT_EVIDENCE",
    InteractionId = "P1_SEARCH_EVIDENCE",
    EntityId = "E01_LISTENER",
    EntitySpawnName = "LISTENER_SPAWN",
    RunStates = {
        PREP = "PREP",
        EXPEDITION = "EXPEDITION",
        OBJECTIVE = "OBJECTIVE",
        EXTRACTION = "EXTRACTION",
        RECOVERY = "RECOVERY",
        COMPLETE = "COMPLETE",
    },
    Trace = {
        MovementInterval = 0.75,
        MovementMinDistance = 3,
        MovementStrength = 2.0,
        SprintStrength = 4.0,
        InteractionStrength = 4.0,
        LightStrength = 1.5,
        Lifetime = 30,
        MaxPerPlayer = 40,
    },
    Door = {
        Name = "P1_CANONICAL_DOOR",
        InteractionId = "P1_DOOR_INTERACT",
        MaxDistance = 12,
        CooldownSeconds = 0.4,
    },
    Evidence = {
        SearchDistance = 12,
        SearchDuration = 1.5,
        RewardAmount = 1,
        RepeatBlocked = true,
    },
    Extraction = {
        Distance = 9,
        CommitSeconds = 2.0,
    },
    Recovery = {
        RespawnDelay = 2.0,
        StartLight = 100,
        StartHealth = 100,
        RunInventoryReset = false,
        BoundedLossFraction = 0.25,
    },
    Listener = {
        MaxHealthDamage = 35,
        AttackRange = 6,
        AttackCooldown = 2.2,
        VisionRange = 28,
        HearingRange = 55,
        TraceRange = 66,
        ThinkPatrol = 0.8,
        ThinkInvestigate = 0.35,
        ThinkChase = 0.15,
        RepathSeconds = 0.8,
        MemorySeconds = 6,
        PatrolSpeed = 8,
        InvestigateSpeed = 10,
        ChaseSpeed = 13,
        SearchSeconds = 5,
        MaxChaseSeconds = 9,
        Leash = 105,
        SignatureIntervals = {0.55, 0.85, 0.70},
        SignatureCooldown = 6.0,
    },
}

return P1Config
